
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_sample_proj'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'snowflake_test'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"
  - "logs"

# To use a variable in a model, hook, or macro, use the {{ var('...') }} function. More information on the var function can be found https://docs.getdbt.com/reference/dbt-jinja-functions/var.
vars:
  'dbt_date:time_zone': 'Australia/Melbourne'
  start_date: '01-JAN-2015' # note 26/5: make sure this is the right date style
  datetoenter: '26-05-2022' # note 26/5: need ot make this dynamic, and rename it

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
quoting:
  database: false
  identifier: false
  schema: false
  
seeds:
  quote_columns: false
  dbt_sample_proj:
    # +enabled: true | false
    # +tags: <string> | [<string>]
    # +pre-hook: <sql-statement> | [<sql-statement>]
    # +post-hook: <sql-statement> | [<sql-statement>]
    # +database: <string>
    jaffles:
      +schema: jaffles
    attr:
      +schema: attr
    mrr:
      +schema: mrr        
    # +full_refresh: <boolean>
    # +meta: {<dictionary>}

models:
  dbt_sample_proj:
    +tags: "dev"
    jaffles:
      +tags: "contains_no_pii"
      +schema: jaffles
      +materialized: view
      staging:
        +tags:
          - "raw_data"
          - "open_data"
        +schema: jaffles
        +materialized: view
    mrr:
      +schema: mrr
      +materialized: table
      utils:
        +schema: mrr
    attr:
      +schema: attr
      +materialized: table    
